# Generated by Django 4.0.6 on 2022-07-30 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kor', models.CharField(max_length=100)),
                ('title_eng', models.CharField(max_length=100)),
                ('poster_url', models.CharField(max_length=900)),
                ('rating_aud', models.CharField(max_length=50)),
                ('rating_cri', models.CharField(max_length=50)),
                ('rating_net', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=100)),
                ('showtimes', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=900)),
                ('movie_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='movie.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
