# Generated by Django 4.0.6 on 2022-07-31 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_title_eng_alter_movie_title_kor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title_eng',
            field=models.CharField(max_length=100),
        ),
    ]
